\hypertarget{classpyrst_1_1pyrst_1_1exceptions_1_1_auth_exception}{}\section{pyrst.\+pyrst.\+exceptions.\+Auth\+Exception Class Reference}
\label{classpyrst_1_1pyrst_1_1exceptions_1_1_auth_exception}\index{pyrst.\+pyrst.\+exceptions.\+Auth\+Exception@{pyrst.\+pyrst.\+exceptions.\+Auth\+Exception}}
Inheritance diagram for pyrst.\+pyrst.\+exceptions.\+Auth\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.709677cm]{classpyrst_1_1pyrst_1_1exceptions_1_1_auth_exception}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hypertarget{classpyrst_1_1pyrst_1_1exceptions_1_1_auth_exception_a60275b6315178b392e46755c9e38246e}{}def {\bfseries \+\_\+\+\_\+repr\+\_\+\+\_\+} (self)\label{classpyrst_1_1pyrst_1_1exceptions_1_1_auth_exception_a60275b6315178b392e46755c9e38246e}

\end{DoxyCompactItemize}


The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
pyrst/exceptions.\+py\end{DoxyCompactItemize}
